#ifndef _COMMON_EVENT_H_
#define _COMMON_EVENT_H_

enum event {
  EVENT_TIMER_INTERRUPT,
  EVENT_IDLE_PRINT_INTERRUPT,
  EVENT_UART1_RX,
  EVENT_UART1_TX,
  EVENT_UART2_RX,
  EVENT_UART2_TX,
  EVENT_UART2_CTS,
  EVENT_UART1_CTS,
  NUM_EVENT_TYPES
};

#endif
