#ifndef _KERNEL__STATUS_H_
#define _KERNEL__STATUS_H_

#define TASK_STATE_ACTIVE 0
#define TASK_STATE_READY 1
#define TASK_STATE_SEND_BLOCKED 2
#define TASK_STATE_RECEIVE_BLOCKED 3
#define TASK_STATE_REPLY_BLOCKED 4
#define TASK_STATE_ZOMBIE 5
#define TASK_STATE_AWAIT_BLOCKED 6

#endif
